services:
  vereinsabstimmung:
    build:
      context: ./next-app
      args:
        NEXT_PUBLIC_SIGNAL_SERVER_URL: https://signal.henryagi.de
    ports:
      - "3334:3000"
    restart: unless-stopped

  signal-server:
    build: ./server
    ports:
      - "9000:9000"
    restart: unless-stopped
